### ISSUE TITLE
Question regarding code reuse

### ISSUE THREAD

**Issue by matthewsmawfield** [gjmcn/tile-maps-eurovis-demo#2]
Dear Graham, I really like the work you have done on observablehq for creating a tile-map; I was wondering what license the code is and if with your permission I could resuse some of your code in my own project? We would put your name as attribution and we would be using tilemaps on a humanitarian information analysis project. Thank you and kind regards. 
https://observablehq.com/@gjmcn/make-a-tile-map

**Comment by gjmcn** [comment]
Glad you like it. You can indeed reuse the code. I have added an MIT license to the tile map notebooks.
